meta_product_name: "Unotes"
meta_title: "Unotes - Learn any skill on Youtube, for free."
meta_description: "Unotes allows you to take course on Youtube, in a better way."
meta_image: "opengraph.jpg" # should exist in `app/assets/images/`
twitter_account: "@LeWagonMrs"   # required for Twitter Cards