meta_product_name: "Unotes"
meta_title: "Unotes - Learn anything online whith ease"
meta_description: "Learn anything on Youtube easily with Unotes, a toolbox made to help you become a better and more efficient student."
meta_image: "opengraph.jpg" # should exist in `app/assets/images/`
twitter_account: "@LeWagonMrs"   # required for Twitter Cards
